<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_599eaa60c0e79',
    'title' => __('Section base fields', 'modularity-form-builder'),
    'fields' => array(
        0 => array(
            'key' => 'field_599eaa6a6c354',
            'label' => __('Content', 'modularity-form-builder'),
            'name' => 'mod_section_content',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        1 => array(
            'key' => 'field_599eab01559ea',
            'label' => __('Section Height', 'modularity-form-builder'),
            'name' => 'mod_section_height',
            'type' => 'radio',
            'instructions' => __('Select the amount of space that the section should take up vertically', 'modularity-form-builder'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'sm' => __('Small (Adapt to content)', 'modularity-form-builder'),
                'md' => __('Medium (Minimum 40 % height)', 'modularity-form-builder'),
                'lg' => __('Large (Minimum 100% height)', 'modularity-form-builder'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        2 => array(
            'key' => 'field_599eabaeaad08',
            'label' => __('Background focus (vertical)', 'modularity-form-builder'),
            'name' => 'mod_section_bg_position_vertical',
            'type' => 'radio',
            'instructions' => __('If the image has to be cropped to fit the view, where is the background focal point vertically?', 'modularity-form-builder'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'top' => __('Top', 'modularity-form-builder'),
                'center' => __('Middle', 'modularity-form-builder'),
                'bottom' => __('Bottom', 'modularity-form-builder'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'center',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        3 => array(
            'key' => 'field_599eac93ead36',
            'label' => __('Background focus (horizontal)', 'modularity-form-builder'),
            'name' => 'mod_section_bg_position_horizontal',
            'type' => 'radio',
            'instructions' => __('If the image has to be cropped to fit the view, where is the background focal point horizontally?', 'modularity-form-builder'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'left' => __('Left', 'modularity-form-builder'),
                'center' => __('Center', 'modularity-form-builder'),
                'bottom' => __('Right', 'modularity-form-builder'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'center',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        4 => array(
            'key' => 'field_599eaf20c6db6',
            'label' => __('Effects', 'modularity-form-builder'),
            'name' => 'mod_section_effect',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'multiply' => __('Multiply - Blend the background image with the background color to make the background image more coherence to your overall profile.', 'modularity-form-builder'),
                'parallax' => __('Parallax - Create some depth with a fixed background in the section. This option creates a illusion that indicates that the content floats on-top of the background.', 'modularity-form-builder'),
            ),
            'allow_custom' => 0,
            'save_custom' => 0,
            'default_value' => array(
            ),
            'layout' => 'vertical',
            'toggle' => 0,
            'return_format' => 'value',
        ),
        5 => array(
            'key' => 'field_599ec93c4b4b7',
            'label' => __('Image position', 'modularity-form-builder'),
            'name' => 'mod_section_image_position',
            'type' => 'radio',
            'instructions' => __('Select on what side of the screen that the image should be placed.', 'modularity-form-builder'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'left' => __('Left', 'modularity-form-builder'),
                'right' => __('Right', 'modularity-form-builder'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'left',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        6 => array(
            'key' => 'field_599ecb18ef407',
            'label' => __('Content position', 'modularity-form-builder'),
            'name' => 'mod_section_content_position',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'top' => __('Top', 'modularity-form-builder'),
                'middle' => __('Middle', 'modularity-form-builder'),
                'bottom' => __('Bottom', 'modularity-form-builder'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        7 => array(
            'key' => 'field_599ecc223a4f6',
            'label' => __('Section margin', 'modularity-form-builder'),
            'name' => 'mod_section_padding',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'sm' => __('Small', 'modularity-form-builder'),
                'md' => __('Medium', 'modularity-form-builder'),
                'lg' => __('Large', 'modularity-form-builder'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}