<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_63ff1e1238bd3',
    'title' => __('Card Section Settings', 'modularity-sections'),
    'fields' => array(
        0 => array(
            'key' => 'field_63ff1e1324e0d',
            'label' => __('Image', 'modularity-sections'),
            'name' => 'image',
            'type' => 'focuspoint',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'preview_size' => 'medium',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
        ),
        1 => array(
            'key' => 'field_63ff1e7124e0e',
            'label' => __('Text', 'modularity-sections'),
            'name' => 'text',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'acfe_textarea_code' => 0,
            'maxlength' => '',
            'rows' => '',
            'placeholder' => '',
            'new_lines' => '',
        ),
        2 => array(
            'key' => 'field_63ff1f0c24e0f',
            'label' => __('Image Position', 'modularity-sections'),
            'name' => 'reverse_columns',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                0 => __('Right', 'modularity-sections'),
                1 => __('Left', 'modularity-sections'),
            ),
            'default_value' => 1,
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'vertical',
            'save_other_choice' => 0,
        ),
        3 => array(
            'key' => 'field_63ff1f5c24e10',
            'label' => __('Height', 'modularity-sections'),
            'name' => 'height',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'content' => __('Content', 'modularity-sections'),
                'full-screen' => __('Full Screen', 'modularity-sections'),
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        4 => array(
            'key' => 'field_63ff205324e11',
            'label' => __('Spacing Top', 'modularity-sections'),
            'name' => 'spacing_top',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Add spacing to top', 'modularity-sections'),
            'default_value' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 0,
        ),
        5 => array(
            'key' => 'field_63ff207624e12',
            'label' => __('Spacing Bottom', 'modularity-sections'),
            'name' => 'spacing_bottom',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Add spacing to bottom', 'modularity-sections'),
            'default_value' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 0,
        ),
        6 => array(
            'key' => 'field_63ff209124e13',
            'label' => __('Full width', 'modularity-sections'),
            'name' => 'stretch',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Stretch to full width of the page', 'modularity-sections'),
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 0,
        ),
        7 => array(
            'key' => 'field_63ff4f61e4ecd',
            'label' => __('Buttons', 'modularity-sections'),
            'name' => 'buttons',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Lägg till rad', 'modularity-sections'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_63ff4f74e4ecf',
                    'label' => __('Label', 'modularity-sections'),
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_63ff4f61e4ecd',
                ),
                1 => array(
                    'key' => 'field_63ff4f6de4ece',
                    'label' => __('URL', 'modularity-sections'),
                    'name' => 'href',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_63ff4f61e4ecd',
                ),
                2 => array(
                    'key' => 'field_63ff4f78e4ed0',
                    'label' => __('Button color', 'modularity-sections'),
                    'name' => 'color',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'primary' => __('Primary', 'modularity-sections'),
                        'secondary' => __('Secondary', 'modularity-sections'),
                        'default' => __('Default', 'modularity-sections'),
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_63ff4f61e4ecd',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-section-card',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/section-card',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}